### ISSUE TITLE
Some small issues in the code during running

### ISSUE THREAD

**Issue by linwk666** [SRKH/S4NN#1]
Thanks for your great work! it is impressive , when runnig the code, i found some small issues, which do not affect the result.
1. at line 100, in S4NN.py when user like me try to run the pretrained model without GPU, some problem appears because the pretrained weight is tranied by GPU. adding codes(boldface) below will solve this problem:
if loading:
    W = np.load(LoadFrom, allow_pickle=True)
**if not GPU:
        for i in range(len(W)):
            W[i] = cupy.asnumpy(W[i])**
2.  at line 234. maybe " best_perf = val " should be replaced by "best_perf = testPerf"
3. the meaning of the delta_o is different from paper, which is actually -delta_o, but it is fixed in the later code:
"W[layer][:, :, 0] -= (delta_o[:, cp.newaxis] * hasFired_o * lr[layer])" which seems to miss a negative sign
same thing seems to happen in delta_h

**Comment by SRKH** [comment]
Thanks for your careful points.
I will update the code accordingly.
